[build]
  command = "hexo generate"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    WWW-Authenticate = "Basic realm=\"Restricted Access\""
    X-Robots-Tag = "noindex"
    Cache-Control = "no-store, no-cache, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 401
  force = true
  headers = {WWW-Authenticate = "Basic realm=\"Restricted Access\""}

[build.environment]
  NODE_VERSION = "18"